export const PERFORM_LOGIN = "PERFORM_LOGIN";
export const CHECK_AUTH = "CHECK_AUTH";
export const LOGOUT = "LOGOUT";

export const FETCHED_FOLDER_CONTENTS = "FETCHED_FOLDER_CONTENTS";
export const FETCHED_FOLDER_PATH = "FETCHED_FOLDER_PATH";
export const FETCHED_FOLDER_INFO = "FETCHED_FOLDER_INFO";
export const OPEN_FOLDER = "OPEN FOLDER";
export const FINISHED_FETCHING_FOLDER = "FINISHED_FETCHING_FOLDER";

export const SEARCH_CHANGED = "SEARCH_CHANGED";
export const REPLACED_SEARCH_ACTION = "REPLACED_SEARCH_ACTION";
export const REMOVED_SEARCH_ACTION = "REMOVED_SEARCH_ACTION"

export const OPENED_CREDENTIAL = "OPENED_CREDENTIAL"
export const CLOSED_CREDENTIAL = "CLOSED_CREDENTIAL"
export const FETCHED_CREDENTIAL = "FETCHED_CREDENTIAL"
export const CREDENTIAL_TOGGLE_EDIT_MODE = "CREDENTIAL_TOGGLE_EDIT_MODE"
export const CREDENTIAL_SET_FETCHING = "CREDENTIAL_SET_FETCHING"
export const UPDATING_CREDENTIAL = "UPDATING_CREDENTIAL"