export const PERFORM_LOGIN = "PERFORM_LOGIN";
export const CHECK_AUTH = "CHECK_AUTH";
export const LOGOUT = "LOGOUT";

export const FETCHED_FOLDER_INFO = "FETCHED_FOLDER_INFO";
export const OPEN_FOLDER = "OPEN FOLDER";
export const FINISHED_FETCHING_FOLDER = "FINISHED_FETCHING_FOLDER";
export const STARTED_FETCHING_FOLDER = "STARTED_FETCHING_FOLDER"

export const SEARCH_CHANGED = "SEARCH_CHANGED";
export const REPLACED_SEARCH_ACTION = "REPLACED_SEARCH_ACTION";
export const REMOVED_SEARCH_ACTION = "REMOVED_SEARCH_ACTION"

export const SET_ADMIN_FOLDER = "SET_ADMIN_FOLDER"
export const FOLDER_ADMIN_SET_EDIT_MODE = "FOLDER_ADMIN_SET_EDIT_MODE"
export const ADMIN_FOLDER_FETCHED = "ADMIN_FOLDER_FETCHED"
export const FOLDER_ADMIN_SET_FETCHING = "FOLDER_ADMIN_SET_FETCHING"
export const FOLDER_BEGIN_CREATION = "FOLDER_BEGIN_CREATION"
export const CLOSED_FOLDER_ADMIN = "CLOSED_ADMIN_FOLDER"
export const ADMIN_FOLDER_USER_LIST_FETCHED = "ADMIN_FOLDER_USER_LIST_FETCHED"

export const SET_ROOT_FOLDERS = "SET_ROOT_FOLDERS"

export const SET_INBOX = "SET_INBOX"
export const SET_OUTBOX = "SET_OUTBOX"
export const SET_MESSAGE_MODAL_OPEN = 'SET_MESSAGE_MODAL_OPEN'
export const SET_MESSAGE_MODAL_FETCHING = 'SET_MESSAGE_MODAL_FETCHING'
export const SET_MESSAGE_MODAL_EDITING = 'SET_MESSAGE_MODAL_EDITING'
export const SET_MESSAGE_MODAL_USER_LIST = 'SET_MESSAGE_MODAL_USER_LIST'
export const SET_MESSAGE_MODAL_CREATING = 'SET_MESSAGE_MODAL_CREATING'
export const SET_BASE_CREDENTIAL_INFO = 'SET_BASE_CREDENTIAL_INFO'
export const SET_MESSAGE_INFO = 'SET_MESSAGE_INFO'
export const SET_SEND_RESULT = 'SET_SEND_RESULT'
export const SET_FOLDER_TREE = 'SET_FOLDER_TREE'
export const CLOSE_MESSAGE_MODAL = 'CLOSE_MESSAGE_MODAL'
export const SET_CHOOSING_CREDENTIAL_LOCATION = 'SET_CHOOSING_CREDENTIAL_LOCATION'
export const SET_MESSAGE_MODAL_READ_ONLY = 'SET_MESSAGE_MODAL_READ_ONLY'

export const APPEND_LOG_LIST = 'APPEND_LOG_LIST'
export const SET_LOG_LIST = 'SET_LOG_LIST'
export const SET_LOG_META = 'SET_LOG_META'
export const SET_LOG_FETCHING = 'SET_LOG_FETCHING'

export const USER_ADMIN_SET_USER_LIST = 'USER_ADMIN_SET_USER_LIST'
export const USER_ADMIN_SET_FETCHING = 'USER_ADMIN_SET_FETCHING'