export const PERFORM_LOGIN = "PERFORM_LOGIN";
export const CHECK_AUTH = "CHECK_AUTH";
export const LOGOUT = "LOGOUT";

export const SEARCH_CHANGED = "SEARCH_CHANGED";
export const REPLACED_SEARCH_ACTION = "REPLACED_SEARCH_ACTION";
export const REMOVED_SEARCH_ACTION = "REMOVED_SEARCH_ACTION"

export const SET_ROOT_FOLDERS = "SET_ROOT_FOLDERS"

export const SET_INBOX = "SET_INBOX"
export const SET_OUTBOX = "SET_OUTBOX"
export const SET_MESSAGE_MODAL_OPEN = 'SET_MESSAGE_MODAL_OPEN'
export const SET_MESSAGE_MODAL_FETCHING = 'SET_MESSAGE_MODAL_FETCHING'
export const SET_MESSAGE_MODAL_EDITING = 'SET_MESSAGE_MODAL_EDITING'
export const SET_MESSAGE_MODAL_USER_LIST = 'SET_MESSAGE_MODAL_USER_LIST'
export const SET_MESSAGE_MODAL_CREATING = 'SET_MESSAGE_MODAL_CREATING'
export const SET_BASE_CREDENTIAL_INFO = 'SET_BASE_CREDENTIAL_INFO'
export const SET_MESSAGE_INFO = 'SET_MESSAGE_INFO'
export const SET_SEND_RESULT = 'SET_SEND_RESULT'
export const SET_FOLDER_TREE = 'SET_FOLDER_TREE'
export const CLOSE_MESSAGE_MODAL = 'CLOSE_MESSAGE_MODAL'
export const SET_CHOOSING_CREDENTIAL_LOCATION = 'SET_CHOOSING_CREDENTIAL_LOCATION'
export const SET_MESSAGE_MODAL_READ_ONLY = 'SET_MESSAGE_MODAL_READ_ONLY'

export const APPEND_LOG_LIST = 'APPEND_LOG_LIST'
export const SET_LOG_LIST = 'SET_LOG_LIST'
export const SET_LOG_META = 'SET_LOG_META'
export const SET_LOG_FETCHING = 'SET_LOG_FETCHING'